'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
Namespace E2000Web
	#Region "Contexts"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	Partial Public Class TestDatabaseEntities1
		Inherits ObjectContext
		#Region "Constructors"

		''' <summary>
		''' Initializes a new TestDatabaseEntities1 object using the connection string found in the 'TestDatabaseEntities1' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=TestDatabaseEntities1", "TestDatabaseEntities1")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestDatabaseEntities1 object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "TestDatabaseEntities1")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		''' <summary>
		''' Initialize a new TestDatabaseEntities1 object.
		''' </summary>
		Public Sub New(ByVal connection As EntityConnection)
			MyBase.New(connection, "TestDatabaseEntities1")
			Me.ContextOptions.LazyLoadingEnabled = True
			OnContextCreated()
		End Sub

		#End Region

		#Region "Partial Methods"

		Partial Private Sub OnContextCreated()
		End Sub

		#End Region

		#Region "ObjectSet Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		Public ReadOnly Property Messages() As ObjectSet(Of Message)
			Get
				If (_Messages Is Nothing) Then
					_Messages = MyBase.CreateObjectSet(Of Message)("Messages")
				End If
				Return _Messages
			End Get
		End Property
		Private _Messages As ObjectSet(Of Message)

		#End Region

		#Region "AddTo Methods"

		''' <summary>
		''' Deprecated Method for adding a new object to the Messages EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
		''' </summary>
		Public Sub AddToMessages(ByVal message As Message)
			MyBase.AddObject("Messages", message)
		End Sub

		#End Region

	End Class

	#End Region

	#Region "Entities"

	''' <summary>
	''' No Metadata Documentation available.
	''' </summary>
	<EdmEntityTypeAttribute(NamespaceName:="TestDatabaseModel", Name:="Message"), Serializable(), DataContractAttribute(IsReference:=True)> _
	Partial Public Class Message
		Inherits EntityObject
		#Region "Factory Method"

		''' <summary>
		''' Create a new Message object.
		''' </summary>
		''' <param name="id">Initial value of the Id property.</param>
		''' <param name="from">Initial value of the From property.</param>
		''' <param name="subject">Initial value of the Subject property.</param>
		''' <param name="sent">Initial value of the Sent property.</param>
		''' <param name="size">Initial value of the Size property.</param>
		''' <param name="hasAttachment">Initial value of the HasAttachment property.</param>
		Public Shared Function CreateMessage(ByVal id As Global.System.Int64, ByVal [from] As Global.System.String, ByVal subject As Global.System.String, ByVal sent As Global.System.DateTime, ByVal size As Global.System.Int64, ByVal hasAttachment As Global.System.Boolean) As Message
			Dim message As New Message()
			message.Id = id
			message.From = Message.From
			message.Subject = subject
			message.Sent = sent
			message.Size = size
			message.HasAttachment = hasAttachment
			Return message
		End Function

		#End Region

		#Region "Primitive Properties"

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
		Public Property Id() As Global.System.Int64
			Get
				Return _Id
			End Get
			Set(ByVal value As System.Int64)
				If _Id <> value Then
					OnIdChanging(value)
					ReportPropertyChanging("Id")
					_Id = StructuralObject.SetValidValue(value)
					ReportPropertyChanged("Id")
					OnIdChanged()
				End If
			End Set
		End Property
		Private _Id As Global.System.Int64
		Partial Private Sub OnIdChanging(ByVal value As Global.System.Int64)
		End Sub
		Partial Private Sub OnIdChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property [From]() As Global.System.String
			Get
				Return _From
			End Get
			Set(ByVal value As System.String)
				OnFromChanging(value)
				ReportPropertyChanging("From")
				_From = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("From")
				OnFromChanged()
			End Set
		End Property
		Private _From As Global.System.String
		Partial Private Sub OnFromChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnFromChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Subject() As Global.System.String
			Get
				Return _Subject
			End Get
			Set(ByVal value As System.String)
				OnSubjectChanging(value)
				ReportPropertyChanging("Subject")
				_Subject = StructuralObject.SetValidValue(value, False)
				ReportPropertyChanged("Subject")
				OnSubjectChanged()
			End Set
		End Property
		Private _Subject As Global.System.String
		Partial Private Sub OnSubjectChanging(ByVal value As Global.System.String)
		End Sub
		Partial Private Sub OnSubjectChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Sent() As Global.System.DateTime
			Get
				Return _Sent
			End Get
			Set(ByVal value As System.DateTime)
				OnSentChanging(value)
				ReportPropertyChanging("Sent")
				_Sent = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Sent")
				OnSentChanged()
			End Set
		End Property
		Private _Sent As Global.System.DateTime
		Partial Private Sub OnSentChanging(ByVal value As Global.System.DateTime)
		End Sub
		Partial Private Sub OnSentChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property Size() As Global.System.Int64
			Get
				Return _Size
			End Get
			Set(ByVal value As System.Int64)
				OnSizeChanging(value)
				ReportPropertyChanging("Size")
				_Size = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("Size")
				OnSizeChanged()
			End Set
		End Property
		Private _Size As Global.System.Int64
		Partial Private Sub OnSizeChanging(ByVal value As Global.System.Int64)
		End Sub
		Partial Private Sub OnSizeChanged()
		End Sub

		''' <summary>
		''' No Metadata Documentation available.
		''' </summary>
		<EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=False), DataMemberAttribute()> _
		Public Property HasAttachment() As Global.System.Boolean
			Get
				Return _HasAttachment
			End Get
			Set(ByVal value As System.Boolean)
				OnHasAttachmentChanging(value)
				ReportPropertyChanging("HasAttachment")
				_HasAttachment = StructuralObject.SetValidValue(value)
				ReportPropertyChanged("HasAttachment")
				OnHasAttachmentChanged()
			End Set
		End Property
		Private _HasAttachment As Global.System.Boolean
		Partial Private Sub OnHasAttachmentChanging(ByVal value As Global.System.Boolean)
		End Sub
		Partial Private Sub OnHasAttachmentChanged()
		End Sub

		#End Region


	End Class

	#End Region


End Namespace
